from django.urls import path
from . import views
urlpatterns = [
      path('signup/', views.signup_page, name='signup'),
      path('login/', views.login_page, name='login'),
      path('logout/', views.logout_page, name='logout'),
      path('dashboard/', views.dashboard, name='dashboard'),
      path('products/', views.products, name='products'),
      path('delete-product/<int:id>/', views.delete_product, name='delete_product'),
      path('billing/', views.billing, name='billing'),
      path('add-to-cart/<int:id>/', views.add_to_cart, name='add_to_cart'),
      path('save-bill/', views.save_bill, name='save_bill'),
      path('barcode-scan/', views.barcode_scan, name='barcode_scan'),
      path('reports/', views.reports, name='reports'),
      path('profit/', views.profit_dashboard, name='profit_dashboard'),
      path('receipt/<int:id>/', views.receipt, name='receipt'),
      path('employees/', views.employees, name='employees'),
      path('delete-employee/<int:id>/', views.delete_employee, name='delete_employee'),
      path('profit-reports/', views.profit_reports, name='profit_reports'),
      path('expenses/', views.expenses, name='expenses'),
      path('delete-expense/<int:id>/', views.delete_expense, name='delete_expense'),
      path('stock-alerts/', views.stock_alert, name='stock_alert'),
      path('suppliers/', views.suppliers, name='suppliers'),
      path('delete-supplier/<int:id>/', views.delete_supplier, name='delete_supplier'),
      path('attendance/', views.attendance, name='attendance'),
      path('delete-attendance/<int:id>/', views.delete_attendance, name='delete_attendance'),
      path('analysis/', views.analytics_dashboard, name='analytics_dashboard'),
]