# Generated by Django 6.0.5 on 2026-05-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_customer_remove_bill_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
