# Generated by Django 6.0.5 on 2026-05-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_employee_address_employee_joining_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_alert',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
