# Generated by Django 6.0.5 on 2026-05-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cgst',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='final_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='sgst',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
